# Generated by Django 2.2.1 on 2019-05-17 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='count',
        ),
    ]
